apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sentinel-deny-checkout-egress
  namespace: sentinel-demo
spec:
  podSelector:
    matchLabels:
      app: checkout
  policyTypes: [Egress]
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
